// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(BluroomContext))]
    [Migration("20241208224758_tasks")]
    partial class tasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Chat", b =>
                {
                    b.Property<int>("Chat_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Chat_id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario1Id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario2Id")
                        .HasColumnType("int");

                    b.HasKey("Chat_id");

                    b.HasIndex("Usuario1Id");

                    b.HasIndex("Usuario2Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("DB.Grupo", b =>
                {
                    b.Property<int>("Grupo_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Grupo_Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Grupo_Id");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("Grupos");
                });

            modelBuilder.Entity("DB.Mensaje", b =>
                {
                    b.Property<int>("Mensaje_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mensaje_Id"));

                    b.Property<int>("Chat_Id")
                        .HasColumnType("int");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Emisor_Id")
                        .HasColumnType("int");

                    b.Property<bool>("EsVisto")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Envio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Usuario_id")
                        .HasColumnType("int");

                    b.HasKey("Mensaje_Id");

                    b.HasIndex("Chat_Id");

                    b.HasIndex("Usuario_id");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("DB.SubGrupo", b =>
                {
                    b.Property<int>("SubgrupoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubgrupoId"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("SubgrupoId");

                    b.HasIndex("GrupoId");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("Subgrupos");
                });

            modelBuilder.Entity("DB.SubGrupoUsuario", b =>
                {
                    b.Property<int>("SubgrupoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SubgrupoId", "UsuarioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SubgruposUsuarios");
                });

            modelBuilder.Entity("DB.Tarea", b =>
                {
                    b.Property<int>("Tarea_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tarea_id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SubGrupoId")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.HasKey("Tarea_id");

                    b.HasIndex("SubGrupoId");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("Tareas");
                });

            modelBuilder.Entity("DB.TareaUsuario", b =>
                {
                    b.Property<int>("Tarea_id")
                        .HasColumnType("int");

                    b.Property<int>("Usuario_Id")
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubgrupoId")
                        .HasColumnType("int");

                    b.Property<int>("TareaUsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TareaUsuarioId"));

                    b.HasKey("Tarea_id", "Usuario_Id");

                    b.HasIndex("SubgrupoId");

                    b.HasIndex("Usuario_Id");

                    b.ToTable("TareaUsuarios");
                });

            modelBuilder.Entity("DB.Usuario", b =>
                {
                    b.Property<int>("Usuario_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Usuario_Id"));

                    b.Property<int>("Avatar")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstaEnLinea")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Usuario_Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("DB.Chat", b =>
                {
                    b.HasOne("DB.Usuario", "Usuario1")
                        .WithMany()
                        .HasForeignKey("Usuario1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DB.Usuario", "Usuario2")
                        .WithMany()
                        .HasForeignKey("Usuario2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario1");

                    b.Navigation("Usuario2");
                });

            modelBuilder.Entity("DB.Grupo", b =>
                {
                    b.HasOne("DB.Usuario", "Creador")
                        .WithMany()
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("DB.Mensaje", b =>
                {
                    b.HasOne("DB.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("Chat_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Usuario_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DB.SubGrupo", b =>
                {
                    b.HasOne("DB.Grupo", "Grupo")
                        .WithMany("Subgrupos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DB.Usuario", null)
                        .WithMany("GruposCreados")
                        .HasForeignKey("Usuario_Id");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("DB.SubGrupoUsuario", b =>
                {
                    b.HasOne("DB.SubGrupo", "Subgrupo")
                        .WithMany("SubgruposUsuarios")
                        .HasForeignKey("SubgrupoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Usuario", "Usuario")
                        .WithMany("SubgruposUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Subgrupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DB.Tarea", b =>
                {
                    b.HasOne("DB.SubGrupo", "SubGrupo")
                        .WithMany("Tareas")
                        .HasForeignKey("SubGrupoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Usuario", "Creador")
                        .WithMany("Tareas")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creador");

                    b.Navigation("SubGrupo");
                });

            modelBuilder.Entity("DB.TareaUsuario", b =>
                {
                    b.HasOne("DB.SubGrupo", null)
                        .WithMany("TareaUsuarios")
                        .HasForeignKey("SubgrupoId");

                    b.HasOne("DB.Tarea", "Tarea")
                        .WithMany("TareaUsuarios")
                        .HasForeignKey("Tarea_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DB.Usuario", "Usuario")
                        .WithMany("TareaUsuarios")
                        .HasForeignKey("Usuario_Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("DB.Grupo", b =>
                {
                    b.Navigation("Subgrupos");
                });

            modelBuilder.Entity("DB.SubGrupo", b =>
                {
                    b.Navigation("SubgruposUsuarios");

                    b.Navigation("TareaUsuarios");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("DB.Tarea", b =>
                {
                    b.Navigation("TareaUsuarios");
                });

            modelBuilder.Entity("DB.Usuario", b =>
                {
                    b.Navigation("GruposCreados");

                    b.Navigation("SubgruposUsuarios");

                    b.Navigation("TareaUsuarios");

                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
